CREATE TABLE persona  (
  id_persona INTEGER GENERATED BY DEFAULT AS IDENTITY,
  nombre  character varying(50)  NOT NULL,
  apellido  character varying(50)  NOT NULL,
  telefono integer NOT NULL,
  PRIMARY KEY ( id_persona )
);

CREATE TABLE huesped (
  id_persona INTEGER,
  nro_documento integer NOT NULL,
  tipo_documento character varying(30)  NOT NULL,
  posicion_iva character varying(50)  NOT NULL,
  fecha_nacimiento  date NOT NULL,
  ocupacion   character varying(50)  NOT NULL,
  nacionalidad   character varying(50)  NOT NULL,
  email   character varying(50) ,
  cuit  integer,
  PRIMARY KEY ( id_persona )
);

CREATE TABLE  reserva  (
   id_reserva  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   fecha_inicio  date NOT NULL,
   fecha_fin  date NOT NULL,
   cant_huespedes  integer,
  PRIMARY KEY ( id_reserva )
);

CREATE TABLE  detalle_reserva  (
   id_detalle_reserva  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   fecha_inicio  date NOT NULL,
   fecha_fin  date NOT NULL,
   descuento  integer DEFAULT 0,
  PRIMARY KEY ( id_detalle_reserva )
);

CREATE TABLE  habitacion  (
   id_habitacion  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   numero  integer NOT NULL,
   piso  integer NOT NULL,
  PRIMARY KEY ( id_habitacion )
);

CREATE TABLE  estado_habitacion  (
   id_estado  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   fecha_desde  date NOT NULL,
   fecha_hasta  date NOT NULL,
   estado   character varying(30)  NOT NULL,
  PRIMARY KEY ( id_estado )
);

CREATE TABLE  tipo_habitacion  (
   id_tipo_habitacion  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nombre   character varying(50)  NOT NULL,
   descripcion   character varying(200)  NOT NULL,
   capacidad  integer NOT NULL,
   costo_noche  integer NOT NULL,
  PRIMARY KEY ( id_tipo_habitacion )
);

CREATE TABLE  direccion  (
   id_direccion  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   calle   character varying(50)  NOT NULL,
   numero  integer NOT NULL,
   departamento  integer,
   piso  integer,
   cod_postal  integer NOT NULL,
   localidad   character varying(50)  NOT NULL,
   pais   character varying(50)  NOT NULL,
   provincia   character varying(50)  NOT NULL,
  PRIMARY KEY ( id_direccion )
);

CREATE TABLE  responsable_pago  (
   id_responsable_pago  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   razon_social   character varying(50)  NOT NULL,
   cuit  integer NOT NULL,
   telefono  integer NOT NULL,
   persona_juridica  boolean NOT NULL,
  PRIMARY KEY ( id_responsable_pago )
);

CREATE TABLE  factura  (
   id_factura  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   numero  integer NOT NULL,
   fecha_emision  date NOT NULL,
   tipo  char NOT NULL,
   estado   character varying(50)  NOT NULL,
   precio_total  float NOT NULL,
  PRIMARY KEY ( id_factura )
);

CREATE TABLE  detalle_factura  (
   id_detalle  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   concepto   character varying(50)  NOT NULL,
   cantidad   character varying(50)  NOT NULL,
   precio_unitario  float NOT NULL,
   precio_total  float NOT NULL,
  PRIMARY KEY ( id_detalle )
);

CREATE TABLE  estadia  (
   id_estadia  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   fecha_inicio  date NOT NULL,
   fecha_fin  date NOT NULL,
   hora_check_in  timestamp NOT NULL,
   hora_check_out  timestamp,
  PRIMARY KEY ( id_estadia )
);

CREATE TABLE  consumo  (
   id_consumo  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nombre   character varying(50)  NOT NULL,
   costo  integer NOT NULL,
  PRIMARY KEY ( id_consumo )
);

CREATE TABLE  consumo_estadia  (
   consumo_id_consumo  integer NOT NULL,
   estadia_id_estadia  integer NOT NULL
);

CREATE TABLE  nota_credito  (
   id_nota_credito  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   numero  integer NOT NULL,
   fecha  date NOT NULL,
  PRIMARY KEY ( id_nota_credito )
);

CREATE TABLE  pago  (
   id_pago  INTEGER GENERATED BY DEFAULT AS IDENTITY,
   moneda   character varying(50)  NOT NULL,
   numero  integer NOT NULL,
   fecha  date NOT NULL,
   monto  float NOT NULL,
   cotizacion  float NOT NULL,
  PRIMARY KEY ( id_pago )
);

CREATE TABLE  medio_pago  (
   id_medio_pago  INTEGER GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ( id_medio_pago )
);

CREATE TABLE  cheque  (
   id_medio_pago  INTEGER NOT NULL,
   nro_cheque  integer NOT NULL,
   banco   character varying(50)  NOT NULL,
   plaza   character varying(50)  NOT NULL,
   fecha_cobro  date,
   es_propio  boolean NOT NULL,
  PRIMARY KEY ( nro_cheque )
);

CREATE TABLE  tarjeta_debito  (
   id_medio_pago  INTEGER NOT NULL,
   marca   character varying(50)  NOT NULL,
   banco_emisor   character varying(50)  NOT NULL
);

CREATE TABLE  tarjeta_credito  (
   id_medio_pago  INTEGER NOT NULL,
   marca   character varying(50)  NOT NULL,
   banco   character varying(50)  NOT NULL
);

COMMENT ON TABLE  huesped  IS 'huesped hereda de persona';

ALTER TABLE  reserva  ADD FOREIGN KEY ( id_reserva ) REFERENCES  persona  ( id_persona ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  huesped  ADD CONSTRAINT  id_persona  FOREIGN KEY ( id_persona ) REFERENCES  persona  ( id_persona ) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE  estadia  ADD FOREIGN KEY ( id_estadia ) REFERENCES  huesped  ( id_persona ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  detalle_reserva  ADD FOREIGN KEY ( id_detalle_reserva ) REFERENCES  reserva  ( id_reserva ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  detalle_reserva  ADD FOREIGN KEY ( id_detalle_reserva ) REFERENCES  habitacion  ( id_habitacion ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  habitacion  ADD FOREIGN KEY ( id_habitacion ) REFERENCES  estado_habitacion  ( id_estado ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  habitacion  ADD FOREIGN KEY ( id_habitacion ) REFERENCES  tipo_habitacion  ( id_tipo_habitacion ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  huesped  ADD FOREIGN KEY ( id_persona ) REFERENCES  direccion  ( id_direccion ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  direccion  ADD FOREIGN KEY ( id_direccion ) REFERENCES  responsable_pago  ( id_responsable_pago ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  responsable_pago  ADD FOREIGN KEY ( id_responsable_pago ) REFERENCES  huesped  ( id_persona ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  factura  ADD FOREIGN KEY ( id_factura ) REFERENCES  responsable_pago  ( id_responsable_pago ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  detalle_factura  ADD FOREIGN KEY ( id_detalle ) REFERENCES  factura  ( id_factura ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  pago  ADD FOREIGN KEY ( id_pago ) REFERENCES  factura  ( id_factura ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  estadia  ADD FOREIGN KEY ( id_estadia ) REFERENCES  reserva  ( id_reserva ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  factura  ADD FOREIGN KEY ( id_factura ) REFERENCES  estadia  ( id_estadia ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  consumo_estadia  ADD FOREIGN KEY ( consumo_id_consumo ) REFERENCES  consumo  ( id_consumo ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  consumo_estadia  ADD FOREIGN KEY ( estadia_id_estadia ) REFERENCES  estadia  ( id_estadia ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  factura  ADD FOREIGN KEY ( id_factura ) REFERENCES  nota_credito  ( id_nota_credito ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  pago  ADD FOREIGN KEY ( id_pago ) REFERENCES  medio_pago  ( id_medio_pago ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  cheque  ADD FOREIGN KEY ( id_medio_pago ) REFERENCES  medio_pago  ( id_medio_pago ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE  tarjeta_debito  ADD FOREIGN KEY ( id_medio_pago ) REFERENCES  medio_pago  ( id_medio_pago ) ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE  tarjeta_credito  ADD FOREIGN KEY ( id_medio_pago ) REFERENCES  medio_pago  ( id_medio_pago ) ON DELETE CASCADE ON UPDATE NO ACTION;
